# Solved Sudokus  Generator

## Importing the needed libraries

In [1]:
import math, random
import numpy as np
import copy

## Settings and main variables of the generator

In [83]:
# SUDOKU SETTINGS
# sudokuDimension indicates the length of the sudoku
sudokuDimension = 9
# It's necessary calculate the size length of each subarray
subArrayDimension = int(math.sqrt(sudokuDimension))
# Automated setting of the sudoku solution
# This creates the list of values for the subarray and shuffles to get a variety of solutions
# listaInicial = list(range(1, sudokuDimension + 1))
# random.shuffle(listaInicial)
# In other case, it's possible to indicate the positions of the values from the first subarray
mainList = [1, 2, 3, 4,5,6,7,8,9]
# It creates the sudoku with full of zeros
sudoku = np.zeros((sudokuDimension, sudokuDimension), dtype=np.uint8)

In [84]:
listsPosition  = 0
isSubArraySolved = False
route = []
structure  = 0
solvedSubArray = 0

## Algorithm function to generate  the solution of each subarray

In [85]:
# This is the algorithm using recursive for choosing the correct option of subarray
counter = 0

def generateSubArray():
    # These are global variables because some ones  are need it in the structure
    global route, listsPosition, isSubArraySolved, solvedSubArray, structure, counter, subArrayDimension
    # if contador % 100 == 0: print("entra en método recursivo {} y tamaño de ruta es {} y ruta {}".format(contador, len(ruta), ruta))
    # print("entra en método recursivo {} y tamaño de ruta es {} y ruta {}".format(contador, len(ruta), ruta))
    counter = counter + 1
    # print(general)
    # If solucionado is True then it's not necessary keep analysing the options
    if isSubArraySolved == False:
        # In each called, the posicionEstructura variable is  used to iterate the  next element in the structured array
        # and are taken the stored values in lista
        # The possibilities are reduced by removing the existing values in ruta variable. NEW UPDATE FOR IMPROVE PERFORMANCE
        listCopy = structure['list'][listsPosition].copy()

        [listCopy.remove(value) if value in route else None for value in structure['list'][listsPosition]]
        # NEW VARIABLE TO IMPROVE THE ALGORITHM TO AVOID SEARCHING IN EXISTING VALUES IN RUTA
        # print("COPIA:", copia)
        # print("ORIGINAL", estructura['lista'][posicionEstructura])
        # print(copia)
        structureCopy = copy.deepcopy(structure)
        [lista.remove(value) if value in route else None for lista in structureCopy['list'] for value in lista]
        # THIS IS FOR AVOID ITERATE WHEN A LIST IS EMPTY AND SKIPS THE PROCESS
        print("comenzando proceso")
        for element in listCopy:
            # The element is added to the ruta variable
            print("agrega  el elemento a la ruta", element)
            route.append(element)
            # print("ruta actual es", ruta)

            structureCopy = copy.deepcopy(structure)
            [structureCopy['list'][i].remove(value) if value in route else None for i, lista in
             enumerate(structure['list']) for value in lista]
            # copiaEstructura = copiaEstructura[copiaEstructura[["len"]].argsort()]
            # print("imprimiendo listas preprocesadas")
            # print(copiaEstructura['lista'][posicionEstructura+1:sudokuDimension])
            # print([False if x == [] else True for x in copiaEstructura['lista'][posicionEstructura+1:sudokuDimension]])

            depthStructure = np.unique(structureCopy['list'][listsPosition + 1:sudokuDimension], return_counts=True)
            # print(analisis)
            isDepthNecessary = all(
                [False if frequency > len(depthStructure[:-1][0][i]) else True for i, frequency in enumerate(depthStructure[-1])])
            # print("análisis de repetidos es igual a:", analisisResult )
            #
            # print((all([False if x == [] else True for x in copiaEstructura['lista'][posicionEstructura+1:sudokuDimension]]) == True) or len(ruta) == 9)
            # All it has to be True to enter in the conditional
            if ((all([False if x == [] else True for x in structureCopy['list'][
                                                          listsPosition + 1:sudokuDimension]]) == True) and isDepthNecessary) or len(
                route) == sudokuDimension:
                # While the posicionEstructura
                if listsPosition < sudokuDimension - 1:
                    # The posicionEstructura is updated for the recursivity and advances the structured array position
                    listsPosition = listsPosition + 1
                    # It calls the same function if there's available places in ruta
                    generateSubArray()
                # When the recursion is finished then the posicionEstructura is less 1 to back at the before lista
                listsPosition = listsPosition - 1
                # If the  lenght of ruta is equals to the sudoku dimension then the solution for that subarray is completed
                if len(route) > sudokuDimension - 1:
                    # The subarray is stored in aglobal  variable to be used in the general structure
                    solvedSubArray = np.array(route).reshape(subArrayDimension, subArrayDimension)
                    # And then it's not necessary keep finding options in the lists
                    isSubArraySolved = True
                    print("subarray  listo")
                    # print(ruta)
                # else: print("no entra en el if y ahora va a eliminar")
                # The last element in the list is removed. This is a part  of backtracking and Depth First Search
            # print("Elimina el último elemento")
            route.pop()
            # These sentences are to break the recursion and avoid easting computational time
            # if isSubArraySolved == True: return
            if isSubArraySolved == True: break

## General structure of the generator

In [86]:

def solveSudoku():
    global sudokuDimension, subArrayDimension, mainList, sudoku, listsPosition, isSubArraySolved, route, structure, solvedSubArray
    # This is the structure of the solved sudoku generator
    #It iterates the subarrays positions in rows
    for i in range(0, sudokuDimension, subArrayDimension):
        # It iterates the subarrays positions in columns
        for x in range(0, sudokuDimension, subArrayDimension):
            # print("-- ALL SUDOKU--")
            # print(sudoku)
            # print("--ALL SUDOKU--")
            # print("CURRENT SUBARRAY:", i + x)
            print(sudoku[i:(i + subArrayDimension), x:(x + subArrayDimension)])
            # subArreglo = sudoku[i:(i+2), x:(x+2)].copy()
            availableValues = []
            solvedSubArray = []
            # It iterates the positions in the  subarray in rows
            #Range is used to delimitate the original positions of the actual subarray in sudoku
            for j in range(i, i + subArrayDimension):
                # It iterates the positions in the  subarray in columns
                for y in range(x, x + subArrayDimension):
                    # lista variable stores  all the values there's in crossing at each position of the subarray
                    recoveredValues = []
                    # It  stores the  values  in crossing  at current row
                    # print("posiciones en filas:",population[0][i,:])
                    recoveredValues = recoveredValues + [x for x in sudoku[j, :] if x > 0]
                    # print("posiciones en columnas:",population[0][:,y])
                    # lista.append(population[0][i,:])
                    # It  stores the  values  in crossing  at current column
                    recoveredValues = recoveredValues + [x for x in sudoku[:, y] if x > 0]
                    # It's not necessary store the repeated values, so these are deleted
                    uniqueRecoveredValues = list(np.unique(recoveredValues))
                    # print("RECOVERED  VALUES", lista)
                    #  the  initial lista variable  is copied  for   removing values that there are not options at that position
                    mainListCopy = mainList.copy()
                    # The found   values and stored in valores are removed from the copy of listaInicial  variable
                    [mainListCopy.remove(x) for x in uniqueRecoveredValues]
                    # print("POSSIBILITES FOR EACH CELL:", valores)
                    # General variable stores the lists of possibilities at each position of the subarray
                    availableValues.append(mainListCopy)
            # Second part
            # print("STARTING THE SECOND PART")
            # The main structured array is created
            structure = np.array([(i, lista, len(lista)) for i, lista in enumerate(availableValues)],
                                  dtype=[('position', 'i4'), ('list', list), ('len', 'i4')])
            # estructura = estructura[estructura[["len"]].argsort()]
            #PosicionEstructura  variable represents the position in the structured array, and it can't be greater than the sudokuDimension
            listsPosition = 0
            # Solucionado variable indicates if the correct  subarray was found
            isSubArraySolved = False
            # Ruta   variable represents all the values for the new subarray in shape of list. The final size has to be equals to sudokuDimension
            route = []
            # This  part is where the generateSubArray function is  called and starts the recursivity
            #It iterates  the  first position of the structured  array with posicionEstructura variable
            generateSubArray()
            # print("SUBARRAY SOLUTION")
            # print(newSubarreglo)
            # The new  generated subarray is  stored in  the actual position  of the sudoku
            sudoku[i:(i + subArrayDimension), x:(x + subArrayDimension)] = solvedSubArray


## Printing the solved sudoku

In [87]:
solveSudoku()

[[0 0 0]
 [0 0 0]
 [0 0 0]]
comenzando proceso
agrega  el elemento a la ruta 1
comenzando proceso
agrega  el elemento a la ruta 2
comenzando proceso
agrega  el elemento a la ruta 3
comenzando proceso
agrega  el elemento a la ruta 4
comenzando proceso
agrega  el elemento a la ruta 5
comenzando proceso
agrega  el elemento a la ruta 6
comenzando proceso
agrega  el elemento a la ruta 7
comenzando proceso
agrega  el elemento a la ruta 8
comenzando proceso
agrega  el elemento a la ruta 9
subarray  listo
[[0 0 0]
 [0 0 0]
 [0 0 0]]
comenzando proceso
agrega  el elemento a la ruta 4
comenzando proceso
agrega  el elemento a la ruta 5
comenzando proceso
agrega  el elemento a la ruta 6
comenzando proceso
agrega  el elemento a la ruta 1
agrega  el elemento a la ruta 2
agrega  el elemento a la ruta 3
agrega  el elemento a la ruta 7
comenzando proceso
agrega  el elemento a la ruta 1
agrega  el elemento a la ruta 2
agrega  el elemento a la ruta 3
agrega  el elemento a la ruta 8
comenzando proceso
agr

In [88]:
sudoku

array([[1, 2, 3, 4, 5, 6, 7, 8, 9],
       [4, 5, 6, 7, 8, 9, 1, 2, 3],
       [7, 8, 9, 1, 2, 3, 4, 5, 6],
       [2, 1, 4, 3, 6, 5, 8, 9, 7],
       [3, 6, 5, 8, 9, 7, 2, 1, 4],
       [8, 9, 7, 2, 1, 4, 3, 6, 5],
       [5, 3, 1, 6, 4, 2, 9, 7, 8],
       [6, 4, 2, 9, 7, 8, 5, 3, 1],
       [9, 7, 8, 5, 3, 1, 6, 4, 2]], dtype=uint8)

In [ ]:
def solve(grid, i=0, j=0):
    i, j = find_next_cell_to_fill(grid, i, j)
    if i == -1:
        return True
    for num in range(1, 17):
        if is_valid(grid, i, j, num):
            grid[i][j] = num
            if solve(grid, i, j):
                return True
            # undo the current cell for backtracking
            grid[i][j] = 0
    return False


def find_next_cell_to_fill(grid, i, j):
    for x in range(i, 16):
        for y in range(j, 16):
            if grid[x][y] == 0:
                return x, y
    for x in range(0, 16):
        for y in range(0, 16):
            if grid[x][y] == 0:
                return x, y
    return -1, -1


def is_valid(grid, i, j, num):
    return not_in_row(grid, i, num) and not_in_col(grid, j, num) and not_in_box(grid, i, j, num)


def not_in_row(grid, row, num):
    for i in range(16):
        if grid[row][i] == num:
            return False
    return True


def not_in_col(grid, col, num):
    for i in range(16):
        if grid[i][col] == num:
            return False
    return True


def not_in_box(grid, row, col, num):
    startRow, startCol = row - row % 4, col - col % 4
    for i in range(4):
        for j in range(4):
            if grid[i + startRow][j + startCol] == num:
                return False
    return True


In [48]:
sudoku

array([[1, 1, 1, 2, 2, 2, 3, 3, 3],
       [1, 1, 1, 2, 2, 2, 3, 3, 3],
       [1, 1, 1, 2, 2, 2, 3, 3, 3],
       [2, 2, 2, 1, 1, 1, 4, 4, 4],
       [2, 2, 2, 1, 1, 1, 4, 4, 4],
       [2, 2, 2, 1, 1, 1, 4, 4, 4],
       [3, 3, 3, 4, 4, 4, 1, 1, 1],
       [3, 3, 3, 4, 4, 4, 1, 1, 1],
       [3, 3, 3, 4, 4, 4, 1, 1, 1]], dtype=uint8)

In [ ]:
cProfile.run("solveSudoku()")

In [ ]:
cProfile.run("solveSudoku()")

In [82]:
cProfile.run("solveSudoku()")

In [63]:
grid = [[1, 2, 3, 0, 0, 0, 0, 0, 0],
        [4, 5, 6, 0, 0, 0, 0, 0, 0],
        [7, 8, 9, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0]]
cProfile.run("solve(grid)")

         3870230 function calls (3708910 primitive calls) in 6.998 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
 161321/1    1.170    0.000    6.998    6.998 2006840376.py:1(solve)
   161321    0.287    0.000    0.287    0.000 2006840376.py:14(find_next_cell_to_fill)
  1451592    1.222    0.000    5.541    0.000 2006840376.py:25(is_valid)
  1451592    2.379    0.000    2.379    0.000 2006840376.py:28(not_in_row)
   353390    0.803    0.000    0.803    0.000 2006840376.py:34(not_in_col)
   291011    1.137    0.000    1.137    0.000 2006840376.py:40(not_in_box)
        1    0.000    0.000    6.998    6.998 <string>:1(<module>)
        1    0.000    0.000    6.998    6.998 {built-in method builtins.exec}
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}




In [48]:
solve(grid)

True

In [49]:
grid

[[1, 2, 3, 4, 5, 6, 7, 8, 9],
 [4, 5, 6, 7, 8, 9, 2, 3, 1],
 [7, 8, 9, 1, 2, 3, 6, 5, 4],
 [3, 6, 5, 8, 9, 7, 4, 1, 2],
 [2, 9, 7, 5, 4, 1, 8, 6, 3],
 [8, 4, 1, 6, 3, 2, 9, 7, 5],
 [5, 3, 4, 9, 7, 8, 1, 2, 6],
 [9, 1, 8, 2, 6, 5, 3, 4, 7],
 [6, 7, 2, 3, 1, 4, 5, 9, 8]]