# Solved Sudokus  Generator

## Importing the needed libraries

In [1]:
import math, random
import numpy as np

## Settings and main variables of the generator

In [26]:
# SUDOKU SETTINGS
# sudokuDimension indicates the length of the sudoku
sudokuDimension = 9
# It's necessary calculate the size length of each subarray
subArrayDimension = int(math.sqrt(sudokuDimension))
# Automated setting of the sudoku solution
# This creates the list of values for the subarray and shuffles to get a variety of solutions
listaInicial = list(range(1, sudokuDimension + 1))
random.shuffle(listaInicial)
# In other case, it's possible to indicate the positions of the values from the first subarray
# listaInicial = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]
# It creates the sudoku with full of zeros
sudoku = np.zeros((sudokuDimension, sudokuDimension), dtype=np.uint8)

## Algorithm function to generate  the solution of each subarray

In [31]:
lista = [[1,2,3,4],[4,5,6,7],[]]
[True if x ==[] else False for x in lista]

[False, False, True]

In [32]:
lista

[[1, 2, 3, 4], [4, 5, 6, 7], []]

In [27]:
# This is the algorithm using recursive for choosing the correct option of subarray
contador = 0
def generateSubArray():

    # These are global variables because some ones  are need it in the structure
    global ruta, posicionEstructura, isSubArraySolved, population, newSubarreglo, estructura, contador
    if contador % 10000 == 0: print("entra en método recursivo {} y tamaño de ruta es {}".format(contador,len(ruta)))
    print("entra en método recursivo {} y tamaño de ruta es {}".format(contador,len(ruta)))
    contador = contador+1
    # print(general)
    # If solucionado is True then it's not necessary keep analysing the options
    if isSubArraySolved == False:
        # In each called, the posicionEstructura variable is  used to iterate the  next element in the structured array
        # and are taken the stored values in lista
        # The possibilities are reduced by removing the existing values in ruta variable. NEW UPDATE FOR IMPROVE PERFORMANCE
        copia = estructura['lista'][posicionEstructura].copy()

        [copia.remove(value) if value in ruta else None for value in estructura['lista'][posicionEstructura]]
        # NEW VARIABLE TO IMPROVE THE ALGORITHM TO AVOID SEARCHING IN EXISTING VALUES IN RUTA
        # print("COPIA:", copia)
        # print("ORIGINAL", estructura['lista'][posicionEstructura])
        print(copia)
        # THIS IS FOR AVOID ITERATE WHEN A LIST IS EMPTY AND SKIPS THE PROCESS
        for elemento in copia:

            # If the elemento of the current element of the structured array in lista  is not on ruta,
            # print(ruta)
            if elemento not in ruta:

                # The element is added to the ruta variable
                ruta.append(elemento)
                # While the posicionEstructura
                if posicionEstructura < sudokuDimension - 1:
                    # The posicionEstructura is updated for the recursivity and advances the structured array position
                    posicionEstructura = posicionEstructura + 1
                    # It calls the same function if there's available places in ruta
                    generateSubArray()
                # When the recursion is finished then the posicionEstructura is less 1 to back at the before lista
                posicionEstructura = posicionEstructura - 1
                # If the  lenght of ruta is equals to the sudoku dimension then the solution for that subarray is completed
                if len(ruta) > sudokuDimension - 1:
                    # Another structured array is created to recovery the real positions and reconstruct the subarray
                    estructuraFinal = np.array(list(zip(estructura['position'], [x for x in ruta])),
                                               dtype=[('position', 'i4'), ('element', 'i4')])
                    # print("impresion  estructura final", estructuraFinal['element'])
                    # The subarray is stored in aglobal  variable to be used in the general structure
                    newSubarreglo = estructuraFinal['element'].reshape(subArrayDimension, subArrayDimension)
                    # And then it's not necessary keep finding options in the lists
                    isSubArraySolved = True
                    print(ruta)
                # The last element in the list is removed. This is a part  of backtracking and Depth First Search
                ruta.pop()
                # These sentences are to break the recursion and avoid easting computational time
                # if isSubArraySolved == True: return
            if isSubArraySolved == True: break

## General structure of the generator

In [28]:
# This is the structure of the solved sudoku generator
#It iterates the subarrays positions in rows
for i in range(0, sudokuDimension, subArrayDimension):
    # It iterates the subarrays positions in columns
    for x in range(0, sudokuDimension, subArrayDimension):
        print("-- ALL SUDOKU--")
        print(sudoku)
        print("--ALL SUDOKU--")
        print("CURRENT SUBARRAY:", i + x)
        print(sudoku[i:(i + subArrayDimension), x:(x + subArrayDimension)])
        # subArreglo = sudoku[i:(i+2), x:(x+2)].copy()
        general = []
        newSubarreglo = []
        # It iterates the positions in the  subarray in rows
        #Range is used to delimitate the original positions of the actual subarray in sudoku
        for j in range(i, i + subArrayDimension):
            # It iterates the positions in the  subarray in columns
            for y in range(x, x + subArrayDimension):
                # lista variable stores  all the values there's in crossing at each position of the subarray
                lista = []
                # It  stores the  values  in crossing  at current row
                # print("posiciones en filas:",population[0][i,:])
                lista = lista + [x for x in sudoku[j, :] if x > 0]
                # print("posiciones en columnas:",population[0][:,y])
                # lista.append(population[0][i,:])
                # It  stores the  values  in crossing  at current column
                lista = lista + [x for x in sudoku[:, y] if x > 0]
                # It's not necessary store the repeated values, so these are deleted
                lista = list(np.unique(lista))
                # print("RECOVERED  VALUES", lista)
                #  the  initial lista variable  is copied  for   removing values that there are not options at that position
                valores = listaInicial.copy()
                # The found   values and stored in valores are removed from the copy of listaInicial  variable
                [valores.remove(x) for x in lista]
                print("POSSIBILITES FOR EACH CELL:", valores)
                # General variable stores the lists of possibilities at each position of the subarray
                general.append(valores)
        # Second part
        print("STARTING THE SECOND PART")
        # The main structured array is created
        estructura = np.array([(i, element, len(element)) for i, element in enumerate(general)],
                              dtype=[('position', 'i4'), ('lista', list), ('len', 'i4')])
        # estructura = estructura[estructura[["len"]].argsort()]
        #PosicionEstructura  variable represents the position in the structured array, and it can't be greater than the sudokuDimension
        posicionEstructura = 0
        # Solucionado variable indicates if the correct  subarray was found
        isSubArraySolved = False
        # Ruta   variable represents all the values for the new subarray in shape of list. The final size has to be equals to sudokuDimension
        ruta = []
        # This  part is where the generateSubArray function is  called and starts the recursivity
        #It iterates  the  first position of the structured  array with posicionEstructura variable
        generateSubArray()
        print("SUBARRAY SOLUTION")
        print(newSubarreglo)
        # The new  generated subarray is  stored in  the actual position  of the sudoku
        sudoku[i:(i + subArrayDimension), x:(x + subArrayDimension)] = newSubarreglo
        # [6, 8, 4, 5, 9, 7, 2, 1, 3]

-- ALL SUDOKU--
[[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]
--ALL SUDOKU--
CURRENT SUBARRAY: 0
[[0 0 0]
 [0 0 0]
 [0 0 0]]
POSSIBILITES FOR EACH CELL: [8, 5, 2, 4, 1, 6, 3, 9, 7]
POSSIBILITES FOR EACH CELL: [8, 5, 2, 4, 1, 6, 3, 9, 7]
POSSIBILITES FOR EACH CELL: [8, 5, 2, 4, 1, 6, 3, 9, 7]
POSSIBILITES FOR EACH CELL: [8, 5, 2, 4, 1, 6, 3, 9, 7]
POSSIBILITES FOR EACH CELL: [8, 5, 2, 4, 1, 6, 3, 9, 7]
POSSIBILITES FOR EACH CELL: [8, 5, 2, 4, 1, 6, 3, 9, 7]
POSSIBILITES FOR EACH CELL: [8, 5, 2, 4, 1, 6, 3, 9, 7]
POSSIBILITES FOR EACH CELL: [8, 5, 2, 4, 1, 6, 3, 9, 7]
POSSIBILITES FOR EACH CELL: [8, 5, 2, 4, 1, 6, 3, 9, 7]
STARTING THE SECOND PART
entra en método recursivo 0 y tamaño de ruta es 0
entra en método recursivo 0 y tamaño de ruta es 0
[8, 5, 2, 4, 1, 6, 3, 9, 7]
entra en método recursivo 1 y tamaño de ruta es 1
[5, 2, 4, 1, 6, 3, 9, 7]

## Printing the solved sudoku

In [29]:
sudoku

array([[8, 5, 2, 4, 1, 6, 3, 9, 7],
       [4, 1, 6, 3, 9, 7, 8, 5, 2],
       [3, 9, 7, 8, 5, 2, 4, 1, 6],
       [5, 8, 4, 2, 6, 1, 9, 7, 3],
       [2, 6, 1, 9, 7, 3, 5, 8, 4],
       [9, 7, 3, 5, 8, 4, 2, 6, 1],
       [1, 2, 8, 6, 4, 5, 7, 3, 9],
       [6, 4, 5, 7, 3, 9, 1, 2, 8],
       [7, 3, 9, 1, 2, 8, 6, 4, 5]], dtype=uint8)

In [41]:
ruta

[11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 1, 5, 23, 25, 8, 7, 9, 10, 2, 4, 3, 6]

In [20]:
ruta

[11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 1, 2, 6, 23, 21, 8, 7, 9, 10]

In [73]:
estructura[estructura[["lista"]].argsort()]

array([(5, list([1]), 1), (1, list([2]), 1), (0, list([3]), 1),
       (7, list([4]), 1), (6, list([5]), 1), (8, list([6]), 1),
       (3, list([7]), 1), (2, list([8]), 1), (4, list([9]), 1)],
      dtype=[('position', '<i4'), ('lista', 'O'), ('len', '<i4')])